PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO operation VALUES(1,'get_foo');
INSERT INTO operation VALUES(2,'get_bar');
INSERT INTO operation VALUES(3,'add_foo');
INSERT INTO operation VALUES(4,'add_bar');
INSERT INTO operation VALUES(5,'show-roles');
INSERT INTO operation VALUES(6,'show-operations');
INSERT INTO role VALUES(1,'admin');
INSERT INTO role VALUES(2,'user');
INSERT INTO permission VALUES(1,1);
INSERT INTO permission VALUES(1,2);
INSERT INTO permission VALUES(1,3);
INSERT INTO permission VALUES(1,4);
INSERT INTO permission VALUES(1,5);
INSERT INTO permission VALUES(1,6);
INSERT INTO permission VALUES(2,1);
INSERT INTO permission VALUES(2,2);
INSERT INTO membership VALUES(1,1);
INSERT INTO membership VALUES(2,2);
COMMIT;
